### ISSUE TITLE
Import only certain languages

### ISSUE THREAD

**Issue by jz222** [bradymholt/cRonstrue#104]
Hi,

I was wondering if it is possible to only import the languages that are needed, because in my application I only need a few languages and importing all the languages is quite a bit of an overhead.

Thanks for your time.

**Comment by bradymholt** [comment]
This would be nice and [has been requested before](https://github.com/bradymholt/cRonstrue/issues/31) but I don't have time to do it and it isn't a priority at this time.  I would welcome a PR for this but am going to close this one.
