### ISSUE TITLE
Wrong pluralization for days

### ISSUE THREAD

**Issue by lildare89** [bradymholt/cRonstrue#113]
Example:
Input: `0 * ? * 2/1 *`
Output: 
Every hour, every 1 day**s** of the week, Monday through Saturday

Expected: Every hour, every 1 day of the week, Monday through Saturday

**Comment by bradymholt** [comment]
What version are you using.

I get:
> Every minute, between aN:00 AM and aN:59 AM, every 1 months, February through December
 on http://bradymholt.github.io/cRonstrue/

**Comment by bradymholt** [comment]
You're probably using: `0 * ? * 2/1` right?

**Comment by bradymholt** [comment]
Fixed by b013556
