### ISSUE TITLE
Create an @angular component

### ISSUE THREAD

**Issue by calamarico** [bradymholt/cRonstrue#121]
Hi @bradymholt!

I want to use in angular8+ your package, I'm thinking to start a create a new ngx-Component for your package, are you agree? And, maybe you have some exist integration for angular?

Regards

**Comment by bradymholt** [comment]
Hi @calamarico - I don't know if an existing Angular component but sounds like a good thing to build.  I haven't worked with Angular > 1.0 so I won't be of much help unfortunately.  I'm assuming  wanting to build a component on your own and depend on this package and if so that sounds like a plan.
