### ISSUE TITLE
cRonstrue does not validate specified values

### ISSUE THREAD

**Issue by ssurkov86** [bradymholt/cRonstrue#123]
cRonstrue does not validate the input cron value as it can be seen from the following example in the demo web site:  
specified value 99 99 99 99 99 99 90
![image](https://user-images.githubusercontent.com/53936349/62769147-16692000-baa1-11e9-9c65-8d4008a22a82.png)

It is expected that the error is thrown in those cases.

Version 1.82.0.

**Comment by bradymholt** [comment]
It's not really the intent of cRonstrue to handle validating a cron expression.  Some rudimentary but not exhaustive validation is done for the purpose of parsing but in general "garbage in, garbage out". 

There are some other packages out there that could be used to validate a cron before passing into cRonstrue:

https://www.npmjs.com/package/cron-validator
https://www.npmjs.com/package/sancronos-validator
