### ISSUE TITLE
Translation with multiple commas not readable

### ISSUE THREAD

**Issue by BilalMakhlouf** [bradymholt/cRonstrue#124]
Hello, I have an issue using your library when I'm facing complex cron expressions like :

`5-45/10,*/5,9 * * * *`

The human translation is not understandable.

**Expected** : Every 10 minutes from 5th minutes to 45th minute, every 5 minutes, at 9th minute
**Actual** : Every 10,* minutes, minutes 5 through 45 past the hour

Thank you for your time.

**Comment by bradymholt** [comment]
@BilalMakhlouf - Thanks.  I'd welcome a pull request to fix this.

**Comment by randallreedjr** [comment]
@bradymholt Have you had a chance to check out my pull request for this issue?

**Comment by randallreedjr** [comment]
Followed up with Brady by email today.

**Comment by bradymholt** [comment]
I am fairly sure a segment with commas indicates multiple values that stand on their own and do not modify a prior value.  

In [ArchLinux cron documentation](https://wiki.archlinux.org/index.php/Cron), it says a comma "List[s] multiple values separated by a comma."

So, I would expect `5-45/10,*/5,9 * * * *` to output something similar to:

>  Every 10 minutes, minutes 5 through 45 past the hour, every 5 minutes, and at 9 minutes past the hour

So, there are 3 values within the segment:
1. 5-45/10
1. */5
1. 9
