### ISSUE TITLE
Quartz / cRonstrue mismatch

### ISSUE THREAD

**Issue by raubel** [bradymholt/cRonstrue#126]
I use cRonstrue to display a readable translation of a Quartz expression.

The cron expression '0 0 6 * * *' is translated by cRonstrue as 'At 06:00 AM'.
Yet this expression is not supported by Quartz: it's not possible to specify both a day-of-month and a day-of-week (see the first note of https://www.quartz-scheduler.org/api/2.3.0/org/quartz/CronExpression.html).

So, as cRonstrue is supposed to support Quartz expressions, I wonder if it is possible to raise an issue in this case (maybe using a specific 'quartzCompliant' config option).

**Comment by bradymholt** [comment]
cRonstrue is not meant to validate cron expressions.  I would recommend validating a cron before passing it into cRonstrue and or Quartz.
