### ISSUE TITLE
{dayOfWeek} through Saturday description inconsistent

### ISSUE THREAD

**Issue by watahak** [bradymholt/cRonstrue#127]
Hi, really digging the library! Having used it for some time, I noticed that the description for day of the week expressions have some inconsistency. Assuming the week is SUN-SAT and dayOfWeekStartIndexZero === true :

0 0 * ? * 0/1 -> Every hour, Sunday through Saturday
**0 0 * ? * 1/1 -> Every hour**
0 0 * ? * 2/1 -> Every hour, Tuesday through Saturday
0 0 * ? * 3/1 -> Every hour, Wednesday through Saturday
0 0 * ? * 4/1 -> Every hour, Thursday through Saturday
0 0 * ? * 5/1 -> Every hour, Friday through Saturday
0 0 * ? * 6/1 -> Every hour, Saturday through Saturday

However from the cron descriptions it seems like the week starts on a Monday, as I am expecting "Every hour, Monday through Saturday"

**Comment by bradymholt** [comment]
Thanks!  Fixed here: https://github.com/bradymholt/cRonstrue/pull/169
