### ISSUE TITLE
Error parsing slightly more complex crons

### ISSUE THREAD

**Issue by manavo** [bradymholt/cRonstrue#133]
I tried adding the cron `4-29/12,39-59/12  * * * *`, and got the output:

> Every 12,39-59 minutes, minutes 4 through 29 past the hour

Which doesn't look quiiiiite right. It should be:

> Every 12th minute from 4 through 29, and every 12th minute from 39 through 59.

**Comment by bradymholt** [comment]
@manavo  - Thanks. I'd welcome a pull request to fix this.

**Comment by manavo** [comment]
Seems like this is actually a duplicate of #124, so closing
