### ISSUE TITLE
Possibility to only allow 5, 6, or 7 part cron expressions

### ISSUE THREAD

**Issue by mortenmoulder** [bradymholt/cRonstrue#136]
As I can read from your readme, this was ported from https://github.com/bradymholt/cron-expression-descriptor

I am using Cronos to validate my expressions in my backend, because you have stated this (cron-expression-descriptor) should not be used to validate expressions: https://github.com/bradymholt/cron-expression-descriptor/issues/125#issuecomment-562707914

Because I'm using Cronos and my backend only supports 5 part expressions (at server-level as well), it would be nice to have some features, other than 24h clock, to tweak this, so every expression with more than 5 parts will give me an error message.

This was already suggested here: https://github.com/bradymholt/cRonstrue/issues/53 but was closed.

However, this should be pretty simple to implement out of the box, so I figured since I now have a good argument, you might want to reconsider.

Thanks

**Comment by bradymholt** [comment]
Added FAQ with some library options: https://github.com/bradymholt/cRonstrue#frequently-asked-questions
