### ISSUE TITLE
Bad Import

### ISSUE THREAD

**Issue by mswilson4040** [bradymholt/cRonstrue#153]
Looks like the version (1.95.0) released today has a bad import.

> ERROR in node_modules/cronstrue/dist/cronstrue.d.ts:1:38 - error TS2691: An import path cannot end with a '.ts' extension. Consider importing './expressionDescriptor' instead.
> 
> 1 import { ExpressionDescriptor } from "./expressionDescriptor.ts";

**Comment by bruceleell** [comment]
+1 same issue, 1.95.0 is bad. @bradymholt could you please check？

**Comment by bradymholt** [comment]
Sorry about that - [Version 1.96.0](https://www.npmjs.com/package/cronstrue/v/1.96.0) has been released and should fix this.
