### ISSUE TITLE
The parser is too permissive

### ISSUE THREAD

**Issue by arseni-mourzenko** [bradymholt/cRonstrue#164]
Hello.

Playing with the different expressions, I noticed a strange behavior. For instance, for the following expression:

```
0 6 211 ? * MON-FRI
```

I would expect the parser to throw an exception. However, currently, the parser happily returns:

> At 99:06 PM, Monday through Friday

Doesn't it make more sense to reject invalid expressions, especially the ones which lead to an invalid date or time?

**Comment by bradymholt** [comment]
Please see [FAQ section](https://github.com/bradymholt/cRonstrue#frequently-asked-questions) regarding parsing on expressions.
