### ISSUE TITLE
How do I specify that the first character is in minutes for 6-character cron?

### ISSUE THREAD

**Issue by WilliamPriorielloGarda** [bradymholt/cRonstrue#166]
For instance "0 3 * * * *".  The first character is interpreted as seconds by cRonstrue, which means the 3 is being treated as minutes. This results in "At 3 minutes past the hour". How do I tell the library to treat the first character as minutes (and the second as hours, and so on...)? This is the standard interpretation of the 6-character cron expression according to my understanding https://en.wikipedia.org/wiki/Cron#CRON_expression

**Comment by bradymholt** [comment]
In short, remove the last segment (`*`) and pass in `0 3 * * *`:

> At 03:00 AM

When a 6 part expression is passed in, the second segment is assumed to be indicate minute and when a 5 part expression is passed in, the second segment is assumed to indicate hour.
