### ISSUE TITLE
The size of the library grows up a few times

### ISSUE THREAD

**Issue by shoonia** [bradymholt/cRonstrue#175]
The size difference between v1.100.0 and v1.102.0 for 4 times 4.7kb to 18.1kb (gzipped)
Here: https://bundlephobia.com/result?p=cronstrue@1.102.0

I think it's happened because thе test library `chai` get into the build 
https://github.com/bradymholt/cRonstrue/blob/885ab14517a54279353e4069ffd0e3fa917d817c/dist/cronstrue.js#L236-L243

Is it possible to exclude the `chai` from the build?

**Comment by bradymholt** [comment]
Thanks for the report.  Fixed in https://github.com/bradymholt/cRonstrue/pull/176.
