### ISSUE TITLE
Parsing of expressions "0/5 8-17 ? * MON-FRI *" and "0 8 1 * ? *"

### ISSUE THREAD

**Issue by joseignaciorc** [bradymholt/cRonstrue#179]
Parsing of expressions `0/5 8-17 ? * MON-FRI *` and `0 8 1 * ? *` does not work as expected in cronstrue

Both expression are valid 6-part cron expressions, and are taken from https://docs.aws.amazon.com/lambda/latest/dg/services-cloudwatchevents-expressions.html

**`0/5 8-17 ? * MON-FRI *`**
the output should be something like like `Every 5 minutes between 8:00 AM and 5:55 PM weekdays` 
but the actual output is `rangeSegment2Description is undefined`

**`0 8 1 * ? *`** 
the output should something like `8:00 AM on the first day of the month` 
but the actual output is `At 01:08 AM, only in undefined`

**Comment by bradymholt** [comment]
I'd welcome a PR.  Thanks.
