### ISSUE TITLE
Supporting next run times

### ISSUE THREAD

**Issue by akashvyom** [bradymholt/cRonstrue#182]
Hi,
We have a use case where we are making use of quartz scheduler and this is exposed via UI but we have a requirement where we want to get the next run times, so that we can show these in UI to users before creating a schedule

**Comment by bradymholt** [comment]
This library simply describes a cron expression and does not support determining "next" scheduled time.

**Comment by akashvyom** [comment]
@bradymholt thanks for confirming, I am willing to spend some time on this, if this is something that is easily possible with some changes can you help me with directions on how to do that.

**Comment by akashvyom** [comment]
@bradymholt thanks, will explore other ways to do it 😄
