### ISSUE TITLE
Support for aliases @daily/@weekly/@monthly...

### ISSUE THREAD

**Issue by vadim-lisovyi** [bradymholt/cRonstrue#190]
cronstrue.toString(@daily)

Error: Expression has only 1 part. At least 5 parts are required.

Thanks for the great lib
It would be cool if this working with the next aliases:

`@yearly`    (non-standard)
`@annually`    (non-standard)
`@monthly`    (non-standard)
`@weekly`    (non-standard)
`@daily`    (non-standard)
`@hourly`    (non-standard)
`@reboot`    (non-standard)

**Comment by bradymholt** [comment]
Thanks for the suggestion.  I would prefer to stay with general / standard cron syntax as much as possible.  If you need this support, you could create a wrapper in your code that translates `@yearly = > 0 0 1 1 *`, for example.
