### ISSUE TITLE
"0 12 * */1 *" should be "“At 12:00 in every month.” but is “At 12:00.”

### ISSUE THREAD

**Issue by alexec** [bradymholt/cRonstrue#191]
https://crontab.guru/#0_12_*_*/1_*

**Comment by bradymholt** [comment]
I think crontab.guru has this one wrong.  Do you have another reference implementation to compare to?

**Comment by alexec** [comment]
I'm thinking that `*/1` ==== `*` - is that correct?

**Comment by bradymholt** [comment]
yes
