### ISSUE TITLE
Cronstrue parses invalid expression

### ISSUE THREAD

**Issue by pconerly** [bradymholt/cRonstrue#198]
The expression `/5 * * * *` is parsed & accepted by cronstrue, but it should raise an error instead.
Cronstrue also gives a strange output for the expression: `Every 5 minutes, starting at minutes past the hour`. For comparison, `*/5 * * * *` produces `Every 5 minutes`.

I'm using cronstrue as an in-browser validator & descriptor of cron expressions in a form, but I need to make sure my form validates properly.

Love the project, thank you for writing it!

If you agree that this is a bug, would you accept a PR for it?

**Comment by bradymholt** [comment]
I have made the decision to not do exhaustive validation of cron expressions in this library.  Please see the [FAQ](https://github.com/bradymholt/cRonstrue#frequently-asked-questions) for details.

**Comment by pconerly** [comment]
That's fair, thanks for the answer @bradymholt
