### ISSUE TITLE
Need support for monthStartIndexZero similar to dayOfWeekStartIndexZero

### ISSUE THREAD

**Issue by tnsardesai** [bradymholt/cRonstrue#209]
We use https://www.npmjs.com/package/cron a popular library for cron.

According to their readme:
```
When specifying your cron values you'll need to make sure that your values fall within the ranges. For instance, some cron's use a 0-7 range for the day of week where both 0 and 7 represent Sunday. We do not. And that is an optimisation.

Seconds: 0-59
Minutes: 0-59
Hours: 0-23
Day of Month: 1-31
Months: 0-11 (Jan-Dec)
Day of Week: 0-6 (Sun-Sat)
```

I see that this library always assumers that months are 1-12. It would be nice to have support for start index zero similar to how there is support for days of the week

**Comment by bradymholt** [comment]
Hmm, I am not familiar with any implementation other than the one you linked to that allows for zero based month.  Do you know of any others?  If not, I think I'd like to stay in line with most all other implementations.

**Comment by tnsardesai** [comment]
To be honest I have not seen any other implementation that do zero based month. I was pretty surprised myself when I found this after noticing a job which was scheduled to run on 1st of July not running until 1st of August. (we are using `cronstrue` for parsing in our frontend but `cron` for scheduling in our `backend`). We have over 7000 jobs scheduled with `cron` so its not easy to just move to another library just to get compatible parsing library.

Would you be opposed to adding this with default false so that people can opt in? I can try my hand at adding this feature.

Btw this library has over 1 million downloads and looks like it is the most popular cron library so I feel adding this feature would improve `cronstrue` by making it more compatible with `cron`. https://www.npmjs.com/search?q=cron&ranking=popularity.

**Comment by bradymholt** [comment]
> I can try my hand at adding this feature. 

Yes, I would welcome a PR that implements this with it defaulting to 1-12.  I think most (all?) of the work would be in `src/cronParser.ts` and you can follow the pattern laid by `dayOfWeekStartIndexZero`.
