### ISSUE TITLE
How do you do multiple daily times?

### ISSUE THREAD

**Issue by OpenSpacesAndPlaces** [bradymholt/cRonstrue#212]
Tried all sorts of variations like this:
At 10:00 AM and At 12:00 PM and At 02:30 PM and At 08:45 PM
At 10:00 AM  every day, At 12:00 PM  every day, At 02:30 PM  every day, At 08:45 PM every day
At 10:00 AM, At 12:00 PM, At 02:30 PM, At 08:45 PM
At 10:00 AM and 12:00 PM and 02:30 PM and 08:45 PM
At 10:00 AM, 12:00 PM, 02:30 PM, 08:45 PM

Is there a way to accomplish this?
Thanks!

**Comment by bradymholt** [comment]
I'm not sure I fully understand this question but you can specify multiple times with a comma.  It sounds like your question is more general to cron syntax and is probably beyond the scope of this project.

![image](https://user-images.githubusercontent.com/759811/132532132-82758aff-7b61-4d10-b5cc-40a0466b1e9a.png)
