### ISSUE TITLE
[Build request] Option to select which locales to include

### ISSUE THREAD

**Issue by danielgindi** [bradymholt/cRonstrue#223]
The locales files weigh over 100KB. An option to select which locales to include - would be great.

**Comment by bradymholt** [comment]
Thanks for the suggestion - @danielgindi  👍 - At least [one other](https://github.com/bradymholt/cRonstrue/issues/31) has requested this as well.  I'd prefer to close this issue and welcome a PR from anyone who would like to implement this.

**Comment by GitMurf** [comment]
cc @danielgindi (initial PR) and @bradymholt (maintainer)... Thanks!

**Comment by GitMurf** [comment]
> @GitMurf Did you see the docs here? https://github.com/bradymholt/cRonstrue?tab=readme-ov-file#i18n

@bradymholt thanks for the quick response! I did read the docs, but I wasn't clear on English specifically. I know the default locale option passed into the toString() method is English, but I was unsure if I still needed to explicitly import English or not?

Thanks a lot for the great library!

P.S. I am happy to do a PR for the readme to clarify what I felt was not quite clear (if you'd like) depending on your answer if English is default locale loaded and therefore you do not need to add the side effect import for English explicitly?

**Comment by GitMurf** [comment]
Thanks @bradymholt ! This is what I needed to confirm. I will submit a PR for a tweak to the README clarifying English as the default... feel free to accept or reject at your discretion :)
