### ISSUE TITLE
Week should start with Sundy , 1 stand for Sundy?

### ISSUE THREAD

**Issue by findmoon** [bradymholt/cRonstrue#228]
I have some confusion about the description of the week.

I find that there are many sources that say 1 in the Cron expression means Sunday, but in the converted readable text representation, the week starts from Monday.

**Comment by bradymholt** [comment]
By default 0 means Sunday so 2 means Tuesday.  You can control this with the `dayOfWeekStartIndexZero ` [option](https://github.com/bradymholt/cRonstrue#options).

**Comment by findmoon** [comment]
Thank you for your reply. And sorry for my inattentiveness. 
Thanks again!
