### ISSUE TITLE
0 12-15 * * * displays wrong description

### ISSUE THREAD

**Issue by flowbartek93** [bradymholt/cRonstrue#237]
I have problem with outputting simply desc such as  Every hour, between 12:00 and 15:00.

Currently, it displays : Every hour, between 12:00 and 15:59. Why is that ?

**Comment by bradymholt** [comment]
What expression are you passing in for that description?

**Comment by flowbartek93** [comment]
Thanks for fixing that. Much appreciated :) However, in our example : `0 12-15 * * *` if I replace first 0 with * like this : 
`* 12-15 * * *` result is also 'Every minute, between 12:00 and 15:59. Would be happy If this case was fixed too :)

**Comment by bradymholt** [comment]
* 12-15 * * * would run every minute from 12:00 up to 15:59 so that description is intentional.  In the original case, with `0` as the minutes, the `and 15:59` part did not make sense because it would only run at 15:00, on the hour.

> Thanks for fixing that. Much appreciated :) However, in our example : `0 12-15 * * *` if I replace first 0 with * like this : `* 12-15 * * *` result is also 'Every minute, between 12:00 and 15:59. Would be happy If this case was fixed too :)
