### ISSUE TITLE
Why only open toString() api

### ISSUE THREAD

**Issue by yongchin0821** [bradymholt/cRonstrue#248]
I am very pleasantly surprised and happy to see this library ❤

I am using it on my work. It is necessary to get the minute, hour and day description separately

I find some functions like `getTimeOfDayDescription()`、`getSecondsDescription()` but these are protected

Why are these APIs not open?

**Comment by bradymholt** [comment]
Hm, I don't recall offhand.  I'm not sure I specifically didn't want them to be called but this has never been something requested.
