### ISSUE TITLE
Incomplete cron expressions with '/' fail silently

### ISSUE THREAD

**Issue by Zsar** [bradymholt/cRonstrue#259]
cRonstrue treats the incomplete value `/5` as valid, but silently fails to parse it:

```typescript
cronstrue.toString("/5 * * * *", {
  throwExceptionOnParseError: true,
  verbose: true,
  locale: "en",
})
```
produces the string "Every 5 minutes, starting at  minutes past the hour, every hour, every day" - note the double whitespace in front of "minutes".

Expected: throws

Reproduced in versions 2.14.0 and 1.125.0 .

Note: `5/` also does not throw but is silently treated as `5`... that may actually be fair.

**Comment by bradymholt** [comment]
`/5 * * * *` does not appear to be a valid expression.

Please see FAQ re: invalid expressions: https://github.com/bradymholt/cRonstrue#frequently-asked-questions

**Comment by Zsar** [comment]
Very well. Figured that, given the output is malformed, it's worth a report anyway.
