### ISSUE TITLE
Incorrect description for days of week when using # character

### ISSUE THREAD

**Issue by joao-borges** [bradymholt/cRonstrue#260]
Hi,

I was trying the following expression for quartz: 
```
1 0 0 ? * 1#1 *
```

According to the specification, day of the week should be 1-7. So the above expression should be translated to:
```
At 12:00:01 AM, on the first Sunday of the month
```

But since cronstrue is using an array of days to find the text, that is being translated to 
```
At 12:00:01 AM, on the first Monday of the month
```

And the library is also accepting day of week `0`which is not supported. And it's returning null for day of week `7` which should be Saturday.

**Comment by bradymholt** [comment]
You probably need to set `dayOfWeekStartIndexZero` [option](https://github.com/bradymholt/cRonstrue#options).
