### ISSUE TITLE
missing of error cases's locale

### ISSUE THREAD

**Issue by salad5f6** [bradymholt/cRonstrue#261]
i having construe as error indicator the error return from error handling is not being translated into defined locale.

` try {
            return cronstrue.toString(props.value || '* * * * *', { locale: 'de' });
        } catch (err: any) {
            console.log(err);
            return err.toString();
        }`
        
        the return string for certain error case is still in English : "Error: Expression has only 3 parts. At least 5 parts are required." | "Error: minutes part must be >= 0 and <= 59"
        
Can you cover this case too ?

**Comment by bradymholt** [comment]
I'd welcome a PR.
