### ISSUE TITLE
double comma in day of month, month, day of week 

### ISSUE THREAD

**Issue by natthawutTKS** [bradymholt/cRonstrue#265]
![image](https://user-images.githubusercontent.com/114980408/203249350-ab61f381-51b2-4ce4-ae48-1b419fe37fb1.png)

i found this bug

**Comment by bradymholt** [comment]
That is not a valid cron expression so it is [expected](https://github.com/bradymholt/cRonstrue#frequently-asked-questions) the output would not be correct.
