### ISSUE TITLE
convert questions every other day

### ISSUE THREAD

**Issue by muyangsx** [bradymholt/cRonstrue#267]
Hi 
     The task is not displayed as living every other day every other day, which seems not continuous. If the interval is greater than one day, it will be displayed as every two days, which looks better. Is it a bug or something?  Look forward to your reply, thank you

for example：

0 12 */1 * * At 12:00 AM
0 17 */2 * * At 12:00 AM, every 2 days

**Comment by bradymholt** [comment]
You can try using the [verbose](https://github.com/bradymholt/cRonstrue#options) option.
