### ISSUE TITLE
Getting "aN:00" instead of 00:00 hour or 12:00 AM.

### ISSUE THREAD

**Issue by vishalgavali** [bradymholt/cRonstrue#270]
I am parsing cron pattern 
> 0 0 /3 * * ?

with below options:
`cronstrue.toString("0 0 /3 * * ?", { verbose: true, dayOfWeekStartIndexZero: false, use24HourTimeFormat: true });`
Getting result as: 
> At 0 minutes past the hour, every 3 hours, starting at **aN**:00, every day

Not sure why it is showing 'aN:00' instead of 00:00 which is expected in this case.
- Using version: 2.21.0

**Comment by bradymholt** [comment]
That expression does not look to the valid.  cRonstrue does not validate expressions.  See the [FAQ](https://github.com/bradymholt/cRonstrue#frequently-asked-questions).
