### ISSUE TITLE
Incorrect translation when both day of month and day of week is set

### ISSUE THREAD

**Issue by vivian-xu** [bradymholt/cRonstrue#272]
**Cron Expression**
`1 1 3 * 3`

**Expected Output**
"在上午 01:01, 限每月 3 号,  **或**星期三"

**Actual Output**
"在上午 01:01, 限每月 3 号, **并且**为星期三"

**Prerequisites**
- [x] The cron expression being passed in is a valid expression.  cRonstrue does not validate expressions and assumes the one you pass is already valid.  See the [FAQ](https://github.com/bradymholt/cRonstrue#frequently-asked-questions) for more details.

**Comment by bradymholt** [comment]
I would welcome a PR to fix this.

**Comment by bradymholt** [comment]
Fixed by https://github.com/bradymholt/cRonstrue/pull/314
