### ISSUE TITLE
"Only" wording for single day of the week

### ISSUE THREAD

**Issue by sashock** [bradymholt/cRonstrue#284]
**Cron Expression**
`23 12 * * SUN`

**Expected Output**
"At 12:23 PM, on Sunday"

**Even Better**
"At 12:23 PM, every Sunday"

**Actual Output**
"At 12:23 PM, **only** on Sunday"

I think that adding the "only" is redundant and/or misleading when the cron runs on a given day of the week. dropping it or replacing with every would make more sense in my optinion.

**Comment by bradymholt** [comment]
I'd welcome a PR for this.
