### ISSUE TITLE
Incorrect time formats used for various locales

### ISSUE THREAD

**Issue by lreis** [bradymholt/cRonstrue#303]
**Cron Expression**
`45 16 * * *`

**Expected Output (pt_BR)**
"Às 16:45"

**Actual Output (pt_BR)**
"Às 04:45 PM"

Time formats are incorrect for the locales listed below. All with the exception of Belarusian are displaying AM/PM, when they should be using 24-hour format. 

- ar
- be
- ca
- es
- fi
- hu
- id
- ja
- nb
- nl
- pt_BR
- sw
- th
- vi
- zh_TW

Please refer to the comparison table at https://yx86wg.csb.app/ to see the values returned by Intl.DateTimeFormat

It looks like the fix would consist of setting the value of [**use24HourTimeFormatByDefault()**](https://github.com/bradymholt/cRonstrue/blob/main/src/i18n/locales/pt_BR.ts#L18C3-L18C33) in the corresponding **/src/i18n/locales/<language>.ts** file to the appropriate value (true is most cases) . I'd be happy to [submit a PR](https://github.com/bradymholt/cRonstrue/compare/main...lreis:cRonstrue:issue-303) if you approve these changes.

**Comment by bradymholt** [comment]
@KirillMikulich (be), @KhalipskiSiarhei (nb), @rikkapro0128 (vi) as the original authors of translations can you confirm these languages should use 24 hour time format rather than AM/PM format?

**Comment by yoav-melamed** [comment]
Please add Hebrew (`he`) on that list of 24-hour clock

**Comment by bradymholt** [comment]
@lreis thanks - I'll accept that PR.

**Comment by lreis** [comment]
@bradymholt thanks - https://github.com/bradymholt/cRonstrue/pull/306

**Comment by lreis** [comment]
Fixed with [v2.43.0](https://github.com/bradymholt/cRonstrue/releases/tag/v2.43.0)
