### ISSUE TITLE
Days are not ordered correctly

### ISSUE THREAD

**Issue by yoav-melamed** [bradymholt/cRonstrue#304]
**Cron Expression**
`0 45 12 22,17,6,30,26 * *`

**Expected Output**
"At 12:45 PM, on day 6, 17, 22, 26, and 30 of the month"

**Actual Output**
"At 12:45 PM, on day 22, 17, 6, 30, and 26 of the month"

**Prerequisites**
- [V] The cron expression being passed in is a valid expression.  cRonstrue does not validate expressions and assumes the one you pass is already valid.  See the [FAQ](https://github.com/bradymholt/cRonstrue#frequently-asked-questions) for more details.

**Comment by bradymholt** [comment]
I'd welcome a PR to order these sequentially.

**Comment by yoav-melamed** [comment]
> I'd welcome a PR to order these sequentially.

I managed to fix it. I can't submit a PR with no option to create a branch.
Could you please guide me on how to submit it for you? (couldn't find it on the CONTRIBUTING.md file)
