### ISSUE TITLE
Support dual form

### ISSUE THREAD

**Issue by Muhammad-Magdi** [bradymholt/cRonstrue#308]
Thank you for your efforts 🙌🏽.
I was trying the package and noticed that the [dual form](https://en.wikipedia.org/wiki/Dual_(grammatical_number)#:~:text=Dual%20(abbreviated%20DU)%20is%20a,single%20unit%20or%20in%20unison.) isn't supported.
If you're planning to support it, I'll be happy to help 🙌🏽.

**Comment by bradymholt** [comment]
Hi @Muhammad-Magdi - I don't have plans to support this.  Would this require a significant restructuring or just changing the content of some of the translations?

**Comment by Muhammad-Magdi** [comment]
I believe it can be done at the translation level. Let me have a try 🙌🏽.
