### ISSUE TITLE
cronstrue.js:230 Locale 'zh_CN' could not be found; falling back to 'en'

### ISSUE THREAD

**Issue by Sharang-heng** [bradymholt/cRonstrue#312]
when I use: cronstrue.toString(record, { locale: 'zh_CN' }
waring:cronstrue.toString(record, { locale: 'zh_CN' }
my version is 2.19.0

**Comment by bradymholt** [comment]
Did you import the locale?  See the [README](https://github.com/bradymholt/cRonstrue?tab=readme-ov-file#i18n) instructions.

Example of it working: https://runkit.com/embed/d7pbucqomrcr
