### ISSUE TITLE
Decimal values not accepted in tzOffset.

### ISSUE THREAD

**Issue by rohit-accuknox** [bradymholt/cRonstrue#321]
**Cron Expression**
`*/21 18 * * *`

**Expected Output**
"Every 21 minutes, between 01:00 PM and 01:59 PM"

**Actual Output**
"Every 21 minutes, between 12:30 PM and 12:30 PM"
![image](https://github.com/bradymholt/cRonstrue/assets/88329339/ba7e0391-01fb-4c56-b3f6-31d0076e6f8d)
tzOffset: -5.5 (IST)

**Prerequisites**
- [ ] The cron expression being passed in is a valid expression.  cRonstrue does not validate expressions and assumes the one you pass is already valid.  See the [FAQ](https://github.com/bradymholt/cRonstrue#frequently-asked-questions) for more details.

**Comment by bradymholt** [comment]
Sorry, this is not supported.
