### ISSUE TITLE
Minute bug

### ISSUE THREAD

**Issue by hajikazuo** [bradymholt/cRonstrue#324]
In this case: 0 9-18/1 10-11 9 * wouldn't it be: every 1 hour, between 09:00 and 18:00, between the 10th and 11th of the month, only in September? For me it appears as At 0 minutes, would that be correct?

**Comment by bradymholt** [comment]
`0 9-18/1 10-11 9 *` > "At 0 minutes past the hour, every 1 hours, between 09:00 AM and 06:00 PM, between day 10 and 11 of the month, only in September"

This looks like expected output here.
