### ISSUE TITLE
Fix Cron Expression Parsing Issue with Invalid Characters

### ISSUE THREAD

**Issue by LeePohHock1007** [bradymholt/cRonstrue#325]
When parsing cron expressions, the system correctly accepts and processes valid expressions like 15 10 * * 1 (which runs at 10:15 AM every Monday). However, when encountering invalid cron expressions such as X Y 5 6 7, the system incorrectly displays the time as aN:0X AM. This is not the expected behavior, and the cron expression parser should handle invalid characters properly or reject them with an appropriate error message.

**Comment by bradymholt** [comment]
Please see the [FAQ](https://github.com/bradymholt/cRonstrue?tab=readme-ov-file#frequently-asked-questions).  The cron is expected the be valid.
