### ISSUE TITLE
Possibly wrong danish translation

### ISSUE THREAD

**Issue by Lars-Sommer** [bradymholt/cRonstrue#327]
**Cron Expression**
`0 3 * * 4`

**Expected Output**
"Kl. 03:00 om torsdagen" or "Kl. 03:00 på torsdage"

**Actual Output**
"Kl 03:00, kun på torsdag"

I am wondering about this translation. In danish it says "Kl 03:00, kun på torsdag" which is a definite singular expression and means that the cron will only activate the following thursday, and not anymore. And this is of course wrong because the cron will actually activate every thursday. 

I think this happens because it is directly translated from the english version "At 03:00 AM, only on Thursday". I am not an english expert, but I think the "only" ("kun" in danish) word in this english context does not exclude other thursdays as it does in danish. It roughly means that this will only happen on thursdays and not in any other weekdays.

Or am I missing something? :) 

@rmja

**Comment by rmja** [comment]
Thanks! Yes, this is a bug. I have created a pr with a fix.
