### ISSUE TITLE
Wrong description for L-N 

### ISSUE THREAD

**Issue by maestroCezar** [bradymholt/cRonstrue#37]
"0 0 0 L-5 * ?" should translate to "5 days before last" instead translated to "between day the last day and 5 of the month"   https://jira.terracotta.org/jira/browse/QTZ-91

**Comment by bradymholt** [comment]
@maestroCezar Want to take a crack at a PR?

**Comment by bradymholt** [comment]
Nevermind - implemented it here: https://github.com/bradymholt/cRonstrue/pull/39
