### ISSUE TITLE
Built-in way to get a string starting with a lowercase letter

### ISSUE THREAD

**Issue by maxharlow** [bradymholt/cRonstrue#40]
Would be nicer to have as a config option when including as part of a longer sentence. Looks like [cron-expression-descriptor](https://github.com/bradymholt/cron-expression-descriptor) does something along these lines.

**Comment by bradymholt** [comment]
I've intentionally not implemented case handling in cRonstrue because it can easily be accomplished outside of the library with a function like this:

```
function lowecaseFirstLetter(string) {
    return string[0].toLowerCase() + string.slice(1);
}
```

So, you could just pass the expression into a function like the above before displaying it.
