### ISSUE TITLE
Problem translating - white space workaround

### ISSUE THREAD

**Issue by maestroCezar** [bradymholt/cRonstrue#42]
"0 0 0 L-2 * ?" throws an exception but adding a space at the end "0 0 0 L-2 * ? " translates correctly.

**Comment by bradymholt** [comment]
Hey @maestroCezar , want submit a PR for this?

**Comment by bradymholt** [comment]
Cannot repo; closing out.

Using cronstrue locally:

```
> npm i cronstrue
+ cronstrue@1.1.0
updated 1 package in 6.505s

> node
> var cronstrue = require('cronstrue');
> cronstrue.toString("0 0 0 L-2 * ?")
'At 12:00 AM, 2 days before the last day of the month'

```

On Demo site:

![image](https://user-images.githubusercontent.com/759811/35053193-0ef3118e-fb6f-11e7-94bf-d857317a3869.png)
