### ISSUE TITLE
FR: include strict mode that does not accept partial expressions

### ISSUE THREAD

**Issue by vilmosioo** [bradymholt/cRonstrue#43]
This feature would help with validation of cron expressions

**Comment by bradymholt** [comment]
Can you elaborate and provide a few examples?

**Comment by vilmosioo** [comment]
Sorry for the late reply. Here is an example:

`0 * * * 1-5` appears as valid however the full cron should be `0 * * ? * 1-5`. 

I understand that the library "Supports 5, 6 (w/ seconds or year), or 7 (w/ seconds and year) part cron expressions", as per the Readme, however it would be nice to have a flag that would only accept strict quartz crons for 6/7 part cron expressions.

**Comment by bradymholt** [comment]
I don't think I fully understand.  `0 * * * 1-5` is a 5 part expression that happens "every hour" (* hour, at 0 minute) and `0 * * ? * 1-5` is a 6 part expression (includes seconds) that happens "every minute" (* hour, * minute, at 0 second).  Both are valid, the second one is just a 6 part cron that specifies seconds.  If you want to ensure it only expects expressions with a certain number of parts (6,7) I would think you could do that from outside the library using `expression.split(" ").length > 5` or something of the like.  I'm going to close this one out but if I am still misunderstanding and you still think there is a use case, I would welcome a PR>
