### ISSUE TITLE
Breaks on comma separated ranged values

### ISSUE THREAD

**Issue by Ramblurr** [bradymholt/cRonstrue#44]
**Input**
```
0 0 0-5/1,8-23/1 * * ?
```

**Expected**: Every hour between 12:00 AM and 5:59 AM, and every hour between 08:00 and 11:59 PM

**Actual**: Every 1,8-23 hours, between 12:00 AM and 05:59 AM

---

Many thanks for this library by the way, it is really fantastic and helpful.

**Comment by bradymholt** [comment]
@Ramblurr Do you know if any cron implementation that supports multiple intervals for a schedule part?
