### ISSUE TITLE
Option to validate cron expression for exact 5/6/7 part

### ISSUE THREAD

**Issue by spk83** [bradymholt/cRonstrue#53]
Thanks for the library. Its very helpful.

I have found one option missing and doing that validation on top of using cRonstrue. 
In certain cases cron expression needs to be in exact 5 parts [ or 6 or 7] based on system you are passing cron expression to. Do you think its a good idea to add an option for this check in cRonstrue?

Let me know your thoughts. Happy to raise PR!

**Comment by bradymholt** [comment]
Thanks!  If you are asking about adding validation to cRonstrue as to the type of expression (i.e. "Only 5 part expression is allowed) then I would say I would prefer to keep validation such as this out of the library itself.  This seems like something a downstream application could easily add as part of its own validation.  I'd prefer to keep cRonstrue focused on describing expressions and not focused on validating cron expression validity or constraining what types of expressions it can handle.

**Comment by bradymholt** [comment]
Added FAQ with some library options: https://github.com/bradymholt/cRonstrue#frequently-asked-questions
