### ISSUE TITLE
Extending or changing translation files

### ISSUE THREAD

**Issue by seveves** [bradymholt/cRonstrue#60]
For example sometimes the German translation does not fit perfectly to our use case or is not as clear as our users would expect it ('At 8 o'clock' should be 'Daily at 8 o'clock' sometimes).
But I don't want to override the language files with some hacky webpack trick so maybe you/we could find a way to extend the API so it would be possible to change specific translations at runtime.

What do you think about this? Of course I would be pleased if I can help you with this 😸

**Comment by bradymholt** [comment]
Can the existing German i18n file be updated to make the translation more natural?  For example, the "At" part in your example is defined here: https://github.com/bradymholt/cRonstrue/blob/master/src/i18n/locales/de.ts#L35 so maybe they could be updated to "Daily at" in German.

I would welcome any PR that updates the translation files to fit more naturally to a language.
