### ISSUE TITLE
Display hours in 24 format

### ISSUE THREAD

**Issue by curunoir** [bradymholt/cRonstrue#69]
Hello,
the library and its i18n features are very cool for non-english users. It could be even more nice if it could display hours on different format commonly used in other countries such as 23:55 instead of 11:55 PM. :)

**Comment by curunoir** [comment]
Nevermind I found the `use24HourTimeFormat` option in the source code. :)

Maybe it could help to mention it in the documentation.

**Comment by bradymholt** [comment]
Thanks - added here: b1fec37fd04ad6f418f48704a590d34545b8b2de
