### ISSUE TITLE
Bug parsing numeric day value

### ISSUE THREAD

**Issue by sbeaney** [bradymholt/cRonstrue#73]
When using the examples provided by Quartz, it appears there's an issue with parsing the day values correctly. 

Using an example from: https://www.quartz-scheduler.net/documentation/quartz-3.x/tutorial/crontrigger.html

Expression: "0 15 10 ? * 6L"
Result: "Fire at 10:15am on the last **Friday** of every month"

In cRonstrue the same expression results in:
"At 10:15 AM, on the last **Saturday** of the month".

Additionally, when testing an example from the Usage section, we get the same issue:
cronstrue.toString("* * * ? * 2-6/2", { dayOfWeekStartIndexZero: false });
> "Every second, every 2 days of the week, Monday through Friday"

When parsing using 1.40.0, it returns " Every second, every 2 days of the week, Tuesday through Saturday"

**Comment by bradymholt** [comment]
By default cRonstrue uses a Day of the Week index starting at zero.  Quartz uses index starting at 0.  If you want cRonstrue to behave like Quartz does, use `{ dayOfWeekStartIndexZero: false }` option.

With that, you'll get what you expect.  Also, I am not seeing the same results with `cronstrue.toString("* * * ? * 2-6/2", { dayOfWeekStartIndexZero: false });`.

Here's an example:
https://runkit.com/bradymholt/5ba56d8252435f0012c29ee1
