### ISSUE TITLE
Failing when run on Node (error:window is not defined)

### ISSUE THREAD

**Issue by Praveenpvs** [bradymholt/cRonstrue#76]
Getting "window is not defined"
    at Object.<anonymous> (D:\Git\Src\App1\node_modules\cronstrue\dist\cronstrue.js:1:262)

Running this program in Node. Did not had a problem with earlier version (like 1.30.0). Is there some thing changed so that I should tell cronstrue to use Node and not Browser context?

--
One more problem in Typescript is not able to load types:
**import * as cronstrue from "cronstrue";** -> resulted in error (saying _error TS7016: Could not find a declaration file for module 'cronstrue'_
This used to work earlier without any explicit type declarations.

So, used var cronstrue = require('cronstrue');

construe.toString("* * * * *"); // -> this resulted in 'windows is not defined" error.

Can you please advise?

Thanks, Praveen

**Comment by bradymholt** [comment]
Thanks for the report.  I just reverted a recent change.  Can you try to install 1.46.0 and let me know if you're still seeing the issue?

**Comment by ztzven** [comment]
Also get window is not defined

**Comment by bradymholt** [comment]
@Praveenpvs Version 1.48.0 should fix this - can you confirm?

**Comment by hash-bang** [comment]
Can confirm

**Comment by Praveenpvs** [comment]
Thanks! I just tested it on 1.50.0. It is working fine in Node.
However the typescript definitions are missing in \dist folder. So, can not use it in TypeScript (unless we create ts definitions exclusively for this)
If it is decided not to include TS definitions within the NPM package, can you do the @types/cronstrue?

**Comment by bradymholt** [comment]
Definitions should be fixed by https://github.com/bradymholt/cRonstrue/pull/81
