### ISSUE TITLE
v1.54.0 Cannot find module 'cronstrue'.

### ISSUE THREAD

**Issue by vadost** [bradymholt/cRonstrue#84]
Hi @bradymholt 
Just connected your package to my Angular project!
npm install cronstrue

```
import { Component } from '@angular/core';
import cronstrue from 'cronstrue';

@Component({
    selector: 'my-app',
    template: `<router-outlet></router-outlet>`,
})
export class AppComponent implements OnInit {
    constructor() { }

  ngOnInit() {
     console.log('cronstrue', cronstrue.toString("* * * * *"));
  }
}
```

Error appears when building a project:
ERROR in src/app/app.component.ts(5,26): error TS2307: Cannot find module 'cronstrue'.

**Comment by bradymholt** [comment]
@vadost Can you see if you have the same problem is version 1.51?  `npm install cronstrue@1.51`?

**Comment by vadost** [comment]
@bradymholt Yes, the same

**Comment by vadost** [comment]
@bradymholt I'm sorry to trouble you! The problem was that the node_modules folder was cached in my docker container! Everything is working!
