### ISSUE TITLE
Error not thrown - when it should be?

### ISSUE THREAD

**Issue by vlio20** [bradymholt/cRonstrue#88]
Hi,
Great repo!!!
try to put this input:
`0/q * * 1 2/w`

you will get the following message:
Every q minutes, every w days of the week, Tuesday through Saturday, only in January

Isn't it a bad formatted input?

**Comment by bradymholt** [comment]
cRonstrue will throw on some parsing errors but this library is not intended to be a general purpose cron parser to ensure it is valid.  I would rather not go down that path with this library as that would introduce significantly to the size.  There might be other libraries that can parse a cron and tell you if it is compliant to the spec.  If you find one, please post back here.

**Comment by vlio20** [comment]
maybe this one: https://github.com/sanjorgek/sancronos-validator
