### ISSUE TITLE
Example implementation of i18n does not match reality

### ISSUE THREAD

**Issue by andreasrein** [bradymholt/cRonstrue#93]
Hello,

I tried to implement the cronstrue package and use it which worked out fine but when I wanted to add the i18n language package i tried to use your example implementing only the minified js-file which didn't work as expected.

I found an old blog post from you were you used this example. This worked out fine:

```
// i18n support
var cronstrue_i18n = require('cronstrue/i18n');
console.log(cronstrue_i18n.toString("*/5 15 * * MON-FRI", { locale: "zh_CN" }));
> "每 5 分钟, 在 03:00 PM, 星期一 到 星期五"

```
Maybe this example should be present in your README ?

Anyways, thank you!

**Comment by bradymholt** [comment]
I'm not sure I understand the problem.  The [i18n browser example](https://github.com/bradymholt/cRonstrue#browser-1)  specifies to load the `dist/cronstrue-i18n.min.js" file from the package in the browser and when I just tested this it worked for me.  Here's a demo, using unpkg.com as an easy way to load the `dist/cronstrue-i18n.min.js` file: https://jsfiddle.net/jsLpm9r1/

Perhaps were you not loading the cronstrue-i18n.min.js file into the browser?
