### ISSUE TITLE
i18n for Chinese, week was translated with an error 

### ISSUE THREAD

**Issue by MurrayFan** [bradymholt/cRonstrue#95]
ERROR: Sunday -> 周一 Monday -> 周二  an so far
Monday is the first day in Chinese,but  is the second day in English

**Comment by bradymholt** [comment]
I don't understand.  Are you suggesting that day "0" should be interpreted as "Monday" for Chinese locale?

Can you give me an example cron expression and what the actual output was versus what you expected the output to be?

**Comment by MurrayFan** [comment]
> I don't understand. Are you suggesting that day "0" should be interpreted as "Monday" for Chinese locale?
> 
> Can you give me an example cron expression and what the actual output was versus what you expected the output to be?

 **Example：** 0 0 0 ? * 4L * 
This express means at 12:00 AM, the last Wednesday Every month,but i18n for Chinese was 

> 在 12:00 AM, 每月的最后一个 星期四
in English:at 12:00 AM, the last **Thursday** Every month

**Comment by MurrayFan** [comment]
Example： 0 0 0 ? * 4L *
This expression means at 12:00 AM, the last Wednesday Every month,but i18n
for Chinese was

在 12:00 AM, 每月的最后一个 星期四

in English:at 12:00 AM, the last Thursday Every month

Brady Holt <notifications@github.com> 于2019年1月7日周一 下午10:49写道：

**Comment by bradymholt** [comment]
You can pass in `dayOfWeekStartIndexZero: false` option to interpret day "1" as being Sunday, rather than "0".

```
require("cronstrue").toString("0 0 0 ? * 4L *", { dayOfWeekStartIndexZero: false });
> "At 12:00 AM, on the last Wednesday of the month"

```
Demo:
https://runkit.com/bradymholt/5c34afb6c236980012047379
