### ISSUE TITLE
The whole danish translation is missing? (locale:"da")

### ISSUE THREAD

**Issue by thorsdal** [bradymholt/cRonstrue#96]
It states that you support danish (locale:"da") in the i18n release. But the cronstrue-i18n.min.js script can't find it (falling back to 'en')

Example: cronstrue.toString("0 12 1 * *", { use24HourTimeFormat:true, locale:"da" })

**Comment by bradymholt** [comment]
Yep - they are there but not exported correctly.  Will be fixes in #97.

**Comment by bradymholt** [comment]
#97 was merged and should be released in a few minutes out to npm.

**Comment by thorsdal** [comment]
Great, thx
