### ISSUE TITLE
Type definition for cronstrue i18n 

### ISSUE THREAD

**Issue by mrbatista** [bradymholt/cRonstrue#98]
Is possible to load type definition when import cronstrue with i18n locale translations?

```js
import cronstrue form 'cronstrue/i18n';
```

**Comment by bradymholt** [comment]
By default, the non i18n [ones are used](https://github.com/bradymholt/cRonstrue/blob/master/package.json#L29).  But, you can import them manually from https://github.com/bradymholt/cRonstrue/blob/master/dist/cronstrue-i18n.d.ts.

**Comment by brndnmtthws** [comment]
How does one import those type definitions manually? I tried adding it to `files` in `tsconfig.json` to no avail.

**Comment by bradymholt** [comment]
This area could use some improvement.

For now, you can import as:
```
import cronstrue from "cronstrue/dist/cronstrue-i18n";
```

which should import type definitions fo i18n.

**Comment by bradymholt** [comment]
https://github.com/bradymholt/cRonstrue/pull/134 should fix this
