### ISSUE TITLE
cronstrue not defined in window

### ISSUE THREAD

**Issue by sorcer1** [bradymholt/cRonstrue#99]
Hello,

I add the scripts from the CDN and i check their status, after the 302 redirect i hav the 200 ok status code.
But when i try to use window.cronstrue, cronstrue is not defined.

```
<script src="https://unpkg.com/cronstrue@latest/dist/cronstrue.min.js" type="text/javascript"></script>
<script src="https://unpkg.com/cronstrue@latest/dist/cronstrue-i18n.min.js" type="text/javascript"></script>
```

**Comment by sorcer1** [comment]
So it's seems there is a problem in the scripts :

![image](https://user-images.githubusercontent.com/584256/52622803-fb7b7180-2eaa-11e9-9275-5434ef1f41f9.png)

**Comment by bradymholt** [comment]
I just tested in jsfiddle and it is working fine for me: https://jsfiddle.net/bradyholt/83y0ofsb/3/ .  Perhaps you are not loading the script from unpkg.com before you reference cronstrue.  I would recommend referencing that JSFiddle to troubleshoot.

**Comment by sorcer1** [comment]
Ok i found the issue, it's only in IE 11 with the "Compatibility view settings" enabled in "Tools" menu.
If i disable the compatibility the script was correctly loaded.
